### ISSUE TITLE
issue with nuxt-bridge

### ISSUE THREAD

**Issue by frederic117** [GrabarzUndPartner/nuxt-speedkit#355]
Hello,
when trying to use speedkit with nuxt-bridge 
i got this error:
× Server
  Compiled with some errors in 1.71m

 ERROR  Failed to compile with 1 errors                                            friendly-errors 09:29:14

 ERROR  in ./node_modules/nuxt-speedkit/plugin.js                                  friendly-errors 09:29:14

Syntax Error: Unexpected token (11:31)                                             friendly-errors 09:29:14

   9 | Vue.use(vFont)
  10 |
> 11 | const fontList = new FontList(<%= options.fonts %>)
     |                                ^
  12 |
  13 | export default (context, inject) => {
  14 |   inject('getFont', fontList.getFont.bind(fontList))

                                                                                   friendly-errors 09:29:14
 @ ./.nuxt/index.js 34:0-70 570:25-52 576:19-46
 @ ./.nuxt/client.js
 @ ./.nuxt/nuxt-speedkit/entry.js
 @ multi ./node_modules/@nuxt/bridge/dist/runtime/capi.plugin.mjs ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/nuxt-speedkit/entry.js
                                                                                   friendly-errors 09:29:14
i Waiting for file changes                                                                         09:29:15
i Memory usage: 1 GB (RSS: 1.27 GB)                                                                09:29:15
i Listening on: http://localhost:3000/                                                             09:29:15
√ Nitro built in 366 ms                                                                            09:29:15
Server Side Rendering Error: Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\Dev\footfoot\footfoot-client\node_modules\nuxt-speedkit\plugin.js: Unexpected token (11:31)

   9 | Vue.use(vFont)
  10 |
> 11 | const fontList = new FontList(<%= options.fonts %>)
     |                                ^
  12 |
  13 | export default (context, inject) => {
  14 |   inject('getFont', fontList.getFont.bind(fontList))
    at Object._raise (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:495:17)
    at Object.unexpected (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:3550:16)
    at Object.parseIdentifierName (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:12697:18)
    at Object.parseIdentifier (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:12677:23)
    at Object.tsParseTypeParameterName (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:10185:27)
    at Object.tsParseTypeParameter (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:7965:22)
    at Object.tsParseDelimitedListWorker (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:7842:23)
    at Object.tsParseDelimitedList (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:7831:25)
    at Object.tsParseBracketedList (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:7877:25)
    at Object.tsParseTypeParameters (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:7986:24)
    at D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:9818:29
    at Object.tryParse (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:3577:20)
    at Object.parseMaybeAssign (D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:9815:24)
    at D:\Dev\footfoot\footfoot-client\node_modules\@babel\parser\lib\index.js:11081:39
    at Object../node_modules/nuxt-speedkit/plugin.js (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:9992:7)
    at __webpack_require__ (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:27:30)
    at Module../.nuxt/index.js (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:2186:86)
    at __webpack_require__ (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:27:30)
    at Module../.nuxt/server.js (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:3823:67)
    at __webpack_require__ (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:27:30)
    at Object.0 (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:33994:18)
    at __webpack_require__ (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:27:30)
    at D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:133:18
    at Object.<anonymous> (D:\Dev\footfoot\footfoot-client\.nuxt\dist\server\server.js:136:10)
(node:22448) UnhandledPromiseRejectionWarning: Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\Dev\footfoot\footfoot-client\node_modules\nuxt-speedkit\plugin.js: Unexpected token (11:31)

Thanks for your help

**Comment by mobi35** [comment]
Is this fixed? I'm having the same error..

**Comment by StephanGerbeth** [comment]
Currently not. At first we will launch version 2 (beta branch) with a better picture and image support and some additional optimization and a migration guide. After that we will prepare the package for nuxt 3.
